# Copyright 2020 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker-compose configuration for the ORD editor + postgres backend database.
#
# The required environment variables should be set in .env to keep everything
# in one place and make it easier to update VMs on GCP.

version: "3"
services:
  db:
    image: "postgres"
    environment:
      # See https://github.com/docker-library/docs/blob/master/postgres/README.md#pgdata.
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${ORD_EDITOR_POSTGRES_PASSWORD}
    volumes:
      - "${ORD_EDITOR_MOUNT}:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  web:
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${ORD_EDITOR_POSTGRES_PASSWORD}
      - GH_CLIENT_ID=${GH_CLIENT_ID}
      - GH_CLIENT_SECRET=${GH_CLIENT_SECRET}
    image: "openreactiondatabase/ord-editor"
    ports:
      - "5000:5000"
