# Copyright 2020 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on: [ pull_request, push ]

env:
  # See https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei.
  CACHE_TARGET: "docker.pkg.github.com/open-reaction-database/ord-interface/interface-cache"
  ORD_SCHEMA_TAG: v0.3.15


jobs:
  test_ord_interface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ord-interface
      - uses: actions/checkout@v2
        with:
          repository: "Open-Reaction-Database/ord-schema"
          ref: ${{ env.ORD_SCHEMA_TAG }}
          path: ord-schema
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.7
      - uses: actions/setup-node@v1
      - name: Setup docker cache
        run: |
          docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" --password="${{ secrets.GITHUB_TOKEN }}"
          docker pull "${CACHE_TARGET}"
      - name: Install ord-schema
        run: |
          cd "${GITHUB_WORKSPACE}/ord-schema"
          pip install -r requirements.txt
          conda install -c rdkit rdkit
          python setup.py install
      - name: Install ord-interface
        run: |
          cd "${GITHUB_WORKSPACE}/ord-interface"
          pip install -r requirements.txt
          python setup.py install
      - name: Run interface tests
        run: |
          cd "${GITHUB_WORKSPACE}/ord-interface/ord_interface"
          npm install puppeteer
          ./run_tests.sh "--cache-from=${CACHE_TARGET}"
      - name: Update docker cache
        run: |
          docker tag openreactiondatabase/ord-interface "${CACHE_TARGET}"
          docker push "${CACHE_TARGET}"
        # NOTE(kearnes): Actions in forks cannot update the cache.
        if: ${{ ! github.event.pull_request.head.repo.fork }}
