# Copyright 2026 Open Reaction Database Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test_ord_interface:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    runs-on: ${{ matrix.os }}
    env:
      PGDATA: $GITHUB_WORKSPACE/rdkit-postgres
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: conda-incubator/setup-miniconda@be893c923ea9cf1cf7cd510fbdde27c7e18cbdcb # v4.1.0
        with:
          miniconda-version: 'latest'
      - name: Setup PostgreSQL and Valkey
        shell: bash -l {0}
        run: |
          # NOTE(skearnes): conda is only used for postgres and valkey (not python).
          conda install -c conda-forge rdkit-postgresql valkey-server
          initdb
      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install ord_interface
        run: uv sync --frozen
      - name: Run tests
        shell: bash -l {0}
        run: |
          uv run coverage erase
          uv run pytest -vv --cov=ord_interface --durations=20
          uv run coverage report

  test_app:
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    # NOTE(skearnes): Docker is not supported on macOS GitLab runners.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install Valkey
        run: sudo apt-get update && sudo apt-get install -y valkey-server
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: Install ord-interface
        run: uv sync --frozen
      - name: Run tests
        run: |
          cd "${GITHUB_WORKSPACE}/ord_interface"
          uv run ./run_tests.sh
